export const BaseData = [
  {
    id: "1",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_FWF2judaujT30K9sMf-tZFhMWpgP6xCemw&s",
    title: "Пылесос Tefal RF-1300",
    price: 10000,
    productRating: 4.5,
    brand: "Tefal",
    type: "Мощный",
    power: 1300,
  },
  {
    id: "2",
    img: "https://thumbs.dreamstime.com/b/falling-drop-rain-blue-earth-image-water-splash-crown-shape-water-splash-crown-shape-falling-drop-earth-140453719.jpg",
    title: "Пылесос Samsung Gf-1500",
    price: 7000,
    productRating: 4.0,
    brand: "Samsung",
    type: "Стандартный",
    power: 1500,
  },
  {
    id: "3",
    img: "https://raw.githubusercontent.com/Codecademy/docs/main/media/bird-thumbnail.jpg",
    title: "Пылесос Tefal Ultra",
    price: 3000,
    productRating: 4.7,
    brand: "Tefal",
    type: "Мощный",
    power: 1700,
  },
  {
    id: "4",
    img: "https://raw.githubusercontent.com/Codecademy/docs/main/media/bird-thumbnail.jpg",
    title: "Пылесос LG 400",
    price: 4000,
    productRating: 4.6,
    brand: "LG",
    type: "Хозяйственный",
    power: 1300,
  },
  {
    id: "5",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_FWF2judaujT30K9sMf-tZFhMWpgP6xCemw&s",
    title: "Пылесос LG WR-U1300",
    price: 5000,
    productRating: 4.5,
    brand: "LG",
    type: "Стандартный",
    power: 1000,
  },
  {
    id: "6",
    img: "https://thumbs.dreamstime.com/b/falling-drop-rain-blue-earth-image-water-splash-crown-shape-water-splash-crown-shape-falling-drop-earth-140453719.jpg",
    title: "Пылесос Tefal Mini",
    price: 1300,
    productRating: 4.0,
    brand: "Tefal",
    type: "Стандартный",
    power: 700,
  },
  {
    id: "7",
    img: "https://raw.githubusercontent.com/Codecademy/docs/main/media/bird-thumbnail.jpg",
    title: "Пылесос Samsung Star",
    price: 8000,
    productRating: 4.7,
    brand: "Samsung",
    type: "Хозяйственный",
    power: 2500,
  },
  {
    id: "8",
    img: "https://raw.githubusercontent.com/Codecademy/docs/main/media/bird-thumbnail.jpg",
    title: "Пылесос Tefal Ultra",
    price: 28990,
    productRating: 4.6,
    brand: "Tefal",
    type: "Мощный",
    power: 500,
  },
  {
    id: "9",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_FWF2judaujT30K9sMf-tZFhMWpgP6xCemw&s",
    title: "Пылесос Tefal RF-1300",
    price: 10000,
    productRating: 4.5,
    brand: "Tefal",
    type: "Мощный",
    power: 1300,
  },
  {
    id: "10",
    img: "https://thumbs.dreamstime.com/b/falling-drop-rain-blue-earth-image-water-splash-crown-shape-water-splash-crown-shape-falling-drop-earth-140453719.jpg",
    title: "Пылесос Samsung Gf-1500",
    price: 7000,
    productRating: 4.0,
    brand: "Samsung",
    type: "Стандартный",
    power: 1500,
  },
  {
    id: "11",
    img: "https://raw.githubusercontent.com/Codecademy/docs/main/media/bird-thumbnail.jpg",
    title: "Пылесос Tefal Ultra",
    price: 3000,
    productRating: 4.7,
    brand: "Tefal",
    type: "Мощный",
    power: 1700,
  },
  {
    id: "12",
    img: "https://raw.githubusercontent.com/Codecademy/docs/main/media/bird-thumbnail.jpg",
    title: "Пылесос LG 400",
    price: 4000,
    productRating: 4.6,
    brand: "LG",
    type: "Хозяйственный",
    power: 1300,
  },
  {
    id: "13",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_FWF2judaujT30K9sMf-tZFhMWpgP6xCemw&s",
    title: "Пылесос LG WR-U1300",
    price: 5000,
    productRating: 4.5,
    brand: "LG",
    type: "Стандартный",
    power: 1000,
  },
  {
    id: "14",
    img: "https://thumbs.dreamstime.com/b/falling-drop-rain-blue-earth-image-water-splash-crown-shape-water-splash-crown-shape-falling-drop-earth-140453719.jpg",
    title: "Пылесос Tefal Mini",
    price: 1300,
    productRating: 4.0,
    brand: "Tefal",
    type: "Стандартный",
    power: "700",
  },
];
