#!/bin/sh
echo '🐶 Husky hook работает!'

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(ts|tsx|js|jsx|json|css|scss)$')

if [ -z "$STAGED_FILES" ]; then
  echo "⚠️  Нет изменений для проверки."
  exit 0
fi

echo "🚀 Запускаем линтинг и форматирование..."

echo "📦 Форматируем измененные файлы..."
bun run prettier --write $STAGED_FILES
git add $STAGED_FILES

echo "📐 Проверка типов..."
if ! bun run lint:type; then
  echo "❌ Ошибка TypeScript"
  exit 1
fi

echo "🔍 Линтинг кода..."
if ! bun run lint; then
  echo "❌ Линтинг завершился с ошибками."
  exit 1
fi

echo "✅ Все проверки пройдены успешно!"
